OCR_TOPIC_EXCHANGE = "finance.ocr.topic"

STAGE_DOCUMENT_NORMALIZE = "document.normalize"
STAGE_OCR_RECOGNIZE = "ocr.recognize"
STAGE_TEXT_CLEAN = "text.clean"
STAGE_QUALITY_VALIDATE = "quality.validate"
STAGE_EMBEDDING_INDEX = "embedding.index"
ROUTING_KEY_DOCUMENT_NORMALIZE = "ocr.document.normalize"
ROUTING_KEY_OCR_RECOGNIZE = "ocr.recognize"
ROUTING_KEY_TEXT_CLEAN = "ocr.text.clean"
ROUTING_KEY_QUALITY_VALIDATE = "ocr.quality.validate"
ROUTING_KEY_EMBEDDING_INDEX = "ocr.embedding.index"
QUEUE_DOCUMENT_NORMALIZE = "finance.ocr.document.normalize"
QUEUE_OCR_RECOGNIZE = "finance.ocr.recognize"
QUEUE_TEXT_CLEAN = "finance.ocr.text.clean"
QUEUE_EMBEDDING_INDEX = "finance.ocr.embedding.index"

TASK_STATUS_RUNNING = "running"
