export const SCENE_CATEGORY_LABELS: Record<string, string> = {
  asset: '资产类型',
  price: '价格位置',
  volume: '成交量/换手',
  trend: '趋势结构',
  valuation: '估值/基本面',
  sentiment: '情绪/异动',
  risk_strategy: '风险/策略',
};

export const TAG_LABELS: Record<string, string> = {
  general: '通用',
  stock: '股票',
  index: '指数',
  convertible_bond: '可转债',
  fund: '基金',
  etf: 'ETF',
  lof: 'LOF',
  index_fund: '指数基金',
  active_fund: '主动基金',
  bond_fund: '债券基金',
  money_fund: '货币基金',
  qdii_fund: 'QDII基金',
  bank_stock: '银行股',
  low_price_stock: '低价股',
  large_cap_stock: '大盘股',
  small_cap_stock: '小盘股',
  price_rise: '上涨',
  price_drop: '下跌',
  sideways: '横盘',
  near_recent_high: '接近高位',
  near_recent_low: '接近低位',
  breakout: '突破',
  pullback: '回调',
  gap_up: '跳空高开',
  gap_down: '跳空低开',
  convertible_high_price_risk: '转债高价风险',
  convertible_low_price_defensive: '转债低价防御',
  fund_nav_rise: '基金净值上涨',
  fund_nav_drop: '基金净值下跌',
  volume_expand: '放量',
  volume_shrink: '缩量',
  high_turnover: '高换手',
  low_turnover: '低换手',
  volume_price_confirm: '量价配合',
  volume_price_divergence: '量价背离',
  volume_spike: '成交量突增',
  volume_dry_up: '成交枯竭',
  fund_share_growth: '基金份额增长',
  fund_share_shrink: '基金份额缩水',
  uptrend: '上升趋势',
  downtrend: '下降趋势',
  range_bound: '区间震荡',
  rebound: '反弹',
  repair: '修复',
  trend_reversal: '趋势反转',
  breakout_from_range: '横盘突破',
  breakdown_from_range: '区间破位',
  continuation: '趋势延续',
  turn_weak: '转弱',
  turn_strong: '转强',
  failed_breakout: '突破失败',
  fund_nav_uptrend: '基金净值上升趋势',
  fund_nav_downtrend: '基金净值下降趋势',
  low_pe: '低PE',
  high_pe: '高PE',
  low_pb: '低PB',
  high_pb: '高PB',
  high_dividend: '高股息',
  valuation_repair: '估值修复',
  valuation_trap: '低估值陷阱',
  fundamental_risk: '基本面风险',
  convertible_low_premium: '转债低溢价率',
  convertible_high_premium: '转债高溢价率',
  convertible_premium_compression: '转债溢价率压缩',
  convertible_premium_expansion: '转债溢价率扩张',
  convertible_debt_floor_support: '转债债底支撑',
  convertible_high_ytm: '转债高到期收益率',
  convertible_low_ytm: '转债低到期收益率',
  convertible_high_conversion_value: '转债高转股价值',
  fund_premium: '基金溢价',
  fund_discount: '基金折价',
  fund_high_fee: '基金高费率',
  fund_large_scale: '基金规模较大',
  fund_small_scale: '基金规模较小',
  fund_tracking_error: '基金跟踪误差',
  fund_high_drawdown: '基金高回撤',
  fund_stable_nav: '基金净值稳定',
  market_attention_rise: '关注度上升',
  short_term_emotion: '短线情绪',
  panic_selling: '恐慌抛售',
  news_driven: '消息驱动',
  policy_driven: '政策驱动',
  sector_rotation: '板块轮动',
  weak_sentiment: '情绪偏弱',
  herding_effect: '羊群效应',
  institutional_behavior: '机构行为',
  convertible_stock_linkage: '转债正股联动',
  convertible_independent_strength: '转债独立走强',
  fund_flow_in: '基金资金流入',
  fund_flow_out: '基金资金流出',
  chase_high_risk: '追高风险',
  false_breakout_risk: '假突破风险',
  liquidity_risk: '流动性风险',
  drawdown_risk: '回撤风险',
  valuation_trap_risk: '估值陷阱风险',
  overheated_risk: '过热风险',
  risk_control: '风险控制',
  position_control: '仓位控制',
  wait_confirm: '等待确认',
  observe_next_day: '观察次日',
  avoid_emotional_trade: '避免情绪交易',
  take_profit_plan: '止盈计划',
  stop_loss_plan: '止损计划',
  convertible_forced_redeem_risk: '转债强赎风险',
  convertible_putback_risk: '转债回售风险',
  convertible_low_rating_risk: '转债低评级风险',
  convertible_small_balance_risk: '转债小规模余额风险',
  convertible_liquidity_risk: '转债流动性风险',
  fund_tracking_deviation_risk: '基金跟踪偏离风险',
  fund_concentration_risk: '基金持仓集中风险',
  fund_credit_risk: '基金信用风险',
  fund_duration_risk: '基金久期风险',
  fund_qdii_fx_risk: 'QDII汇率风险',
  fund_liquidity_risk: '基金流动性风险',
};

export const CATEGORY_TAG_TYPES: Record<string, string> = {
  asset: 'primary',
  price: 'success',
  volume: 'warning',
  trend: '',
  valuation: 'info',
  sentiment: 'danger',
  risk_strategy: 'danger',
};

export const VALID_TAGS_BY_CATEGORY: Record<string, string[]> = {
  asset: [
    'general', 'stock', 'index', 'convertible_bond', 'fund',
    'etf', 'lof', 'index_fund', 'active_fund', 'bond_fund', 'money_fund', 'qdii_fund',
    'bank_stock', 'low_price_stock', 'large_cap_stock', 'small_cap_stock',
  ],
  price: [
    'price_rise', 'price_drop', 'sideways', 'near_recent_high',
    'near_recent_low', 'breakout', 'pullback', 'gap_up', 'gap_down',
    'convertible_high_price_risk', 'convertible_low_price_defensive',
    'fund_nav_rise', 'fund_nav_drop',
  ],
  volume: [
    'volume_expand', 'volume_shrink', 'high_turnover', 'low_turnover',
    'volume_price_confirm', 'volume_price_divergence', 'volume_spike', 'volume_dry_up',
    'fund_share_growth', 'fund_share_shrink',
  ],
  trend: [
    'uptrend', 'downtrend', 'range_bound', 'rebound',
    'pullback', 'repair', 'trend_reversal', 'breakout_from_range',
    'breakdown_from_range', 'continuation', 'turn_weak', 'turn_strong',
    'failed_breakout', 'fund_nav_uptrend', 'fund_nav_downtrend',
  ],
  valuation: [
    'low_pe', 'high_pe', 'low_pb', 'high_pb', 'high_dividend',
    'valuation_repair', 'valuation_trap', 'fundamental_risk',
    'convertible_low_premium', 'convertible_high_premium',
    'convertible_premium_compression', 'convertible_premium_expansion',
    'convertible_debt_floor_support', 'convertible_high_ytm',
    'convertible_low_ytm', 'convertible_high_conversion_value',
    'fund_premium', 'fund_discount', 'fund_high_fee', 'fund_large_scale',
    'fund_small_scale', 'fund_tracking_error', 'fund_high_drawdown', 'fund_stable_nav',
  ],
  sentiment: [
    'market_attention_rise', 'short_term_emotion', 'panic_selling',
    'news_driven', 'policy_driven', 'sector_rotation', 'weak_sentiment',
    'herding_effect', 'institutional_behavior',
    'convertible_stock_linkage', 'convertible_independent_strength',
    'fund_flow_in', 'fund_flow_out',
  ],
  risk_strategy: [
    'chase_high_risk', 'false_breakout_risk', 'liquidity_risk',
    'drawdown_risk', 'valuation_trap_risk', 'overheated_risk',
    'risk_control', 'position_control', 'wait_confirm', 'observe_next_day',
    'avoid_emotional_trade', 'take_profit_plan', 'stop_loss_plan',
    'convertible_forced_redeem_risk', 'convertible_putback_risk',
    'convertible_low_rating_risk', 'convertible_small_balance_risk',
    'convertible_liquidity_risk', 'fund_tracking_deviation_risk',
    'fund_concentration_risk', 'fund_credit_risk', 'fund_duration_risk',
    'fund_qdii_fx_risk', 'fund_liquidity_risk',
  ],
};
