export const SCENE_CATEGORY_LABELS: Record<string, string> = {
  asset: '资产类型',
  price: '价格位置',
  volume: '成交量/换手',
  trend: '趋势结构',
  valuation: '估值/基本面',
  sentiment: '情绪/异动',
  risk_strategy: '风险/策略',
};

export const TAG_LABELS: Record<string, string> = {
  general: '通用',
  stock: '股票',
  index: '指数',
  convertible_bond: '可转债',
  fund: '基金',
  bank_stock: '银行股',
  low_price_stock: '低价股',
  large_cap_stock: '大盘股',
  small_cap_stock: '小盘股',
  price_rise: '上涨',
  price_drop: '下跌',
  sideways: '横盘',
  near_recent_high: '接近高位',
  near_recent_low: '接近低位',
  breakout: '突破',
  pullback: '回调',
  gap_up: '跳空高开',
  gap_down: '跳空低开',
  volume_expand: '放量',
  volume_shrink: '缩量',
  high_turnover: '高换手',
  low_turnover: '低换手',
  volume_price_confirm: '量价配合',
  volume_price_divergence: '量价背离',
  volume_spike: '成交量突增',
  volume_dry_up: '成交枯竭',
  uptrend: '上升趋势',
  downtrend: '下降趋势',
  range_bound: '区间震荡',
  rebound: '反弹',
  repair: '修复',
  trend_reversal: '趋势反转',
  breakout_from_range: '横盘突破',
  breakdown_from_range: '区间破位',
  continuation: '趋势延续',
  turn_weak: '转弱',
  turn_strong: '转强',
  failed_breakout: '突破失败',
  low_pe: '低PE',
  high_pe: '高PE',
  low_pb: '低PB',
  high_pb: '高PB',
  high_dividend: '高股息',
  valuation_repair: '估值修复',
  valuation_trap: '低估值陷阱',
  fundamental_risk: '基本面风险',
  market_attention_rise: '关注度上升',
  short_term_emotion: '短线情绪',
  panic_selling: '恐慌抛售',
  news_driven: '消息驱动',
  policy_driven: '政策驱动',
  sector_rotation: '板块轮动',
  weak_sentiment: '情绪偏弱',
  herding_effect: '羊群效应',
  institutional_behavior: '机构行为',
  chase_high_risk: '追高风险',
  false_breakout_risk: '假突破风险',
  liquidity_risk: '流动性风险',
  drawdown_risk: '回撤风险',
  valuation_trap_risk: '估值陷阱风险',
  overheated_risk: '过热风险',
  risk_control: '风险控制',
  position_control: '仓位控制',
  wait_confirm: '等待确认',
  observe_next_day: '观察次日',
  avoid_emotional_trade: '避免情绪交易',
  take_profit_plan: '止盈计划',
  stop_loss_plan: '止损计划',
};

export const CATEGORY_TAG_TYPES: Record<string, string> = {
  asset: 'primary',
  price: 'success',
  volume: 'warning',
  trend: '',
  valuation: 'info',
  sentiment: 'danger',
  risk_strategy: 'danger',
};

export const VALID_TAGS_BY_CATEGORY: Record<string, string[]> = {
  asset: [
    'general', 'stock', 'index', 'convertible_bond', 'fund',
    'bank_stock', 'low_price_stock', 'large_cap_stock', 'small_cap_stock',
  ],
  price: [
    'price_rise', 'price_drop', 'sideways', 'near_recent_high',
    'near_recent_low', 'breakout', 'pullback', 'gap_up', 'gap_down',
  ],
  volume: [
    'volume_expand', 'volume_shrink', 'high_turnover', 'low_turnover',
    'volume_price_confirm', 'volume_price_divergence', 'volume_spike', 'volume_dry_up',
  ],
  trend: [
    'uptrend', 'downtrend', 'range_bound', 'rebound',
    'pullback', 'repair', 'trend_reversal', 'breakout_from_range',
    'breakdown_from_range', 'continuation', 'turn_weak', 'turn_strong',
    'failed_breakout',
  ],
  valuation: [
    'low_pe', 'high_pe', 'low_pb', 'high_pb', 'high_dividend',
    'valuation_repair', 'valuation_trap', 'fundamental_risk',
  ],
  sentiment: [
    'market_attention_rise', 'short_term_emotion', 'panic_selling',
    'news_driven', 'policy_driven', 'sector_rotation', 'weak_sentiment',
    'herding_effect', 'institutional_behavior',
  ],
  risk_strategy: [
    'chase_high_risk', 'false_breakout_risk', 'liquidity_risk',
    'drawdown_risk', 'valuation_trap_risk', 'overheated_risk',
    'risk_control', 'position_control', 'wait_confirm', 'observe_next_day',
    'avoid_emotional_trade', 'take_profit_plan', 'stop_loss_plan',
  ],
};
